CREATE TABLE IF NOT EXISTS leituras (
	id SERIAL PRIMARY KEY,
	sensor_id INTEGER, 
	umidade INTEGER,
	vibracao INTEGER,
	botao INTEGER,
	timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

SELECT * FROM leituras